# Generated by Django 4.2.27 on 2025-12-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('information', 'Information'), ('evenement', 'Événement')], default='information', max_length=20),
        ),
    ]
