# Generated by Django 4.2.27 on 2025-12-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='event_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='event_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
