# Generated by Django 4.2.27 on 2025-12-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
    ]
