# Generated by Django 4.2.27 on 2026-01-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='presentation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organisation',
            name='public_image',
            field=models.ImageField(blank=True, null=True, upload_to='org_public/'),
        ),
    ]
