# Generated by Django 4.2.27 on 2026-03-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_organisation_presentation_organisation_public_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="horaires",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="OrganisationPublicDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="org_public_documents/")),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_documents",
                        to="core.organisation",
                    ),
                ),
            ],
        ),
    ]
